version: "3.8"
services:
  app:
    image: grow-app:latest
    container_name: grow-app
    build: app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/pi/certbot/conf:/etc/letsencrypt
    depends_on:
      - api
  api:
    image: grow-server:latest
    container_name: grow-api
    build: server
    environment:
      REDIS_HOSTNAME: redis
      DATABASE_HOSTNAME: mariadb
    depends_on:
      - redis
      - sql
  worker:
    image: grow-server:latest
    container_name: grow-worker
    build: server
    command: python main.py
    environment:
      REDIS_HOSTNAME: redis
      DATABASE_HOSTNAME: mariadb
    depends_on:
      - redis
      - sql
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
  sql:
    image: mariadb:10.8.3
    container_name: mariadb
    environment:
      MARIADB_DATABASE: grow
      MARIADB_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  certbot:
    image: certbot/dns-cloudflare:arm64v8-v1.25.0
    container_name: certbot
    volumes: 
      - /home/pi/certbot/conf:/etc/letsencrypt
      - /home/pi/certbot/logs:/var/log/letsencrypt
      - /home/pi/certbot/cloudflare.ini:/cloudflare.ini
    command: certonly --dns-cloudflare --dns-cloudflare-credentials /cloudflare.ini --force-renewal --email ben@okkema.org -d grow.okkema.org --agree-tos