version: "3.8"
services:
  app:
    image: grow-app:latest
    container_name: grow-app
    build: app
    ports:
      - "80:80"
    volumes:
      - /home/${GH_RUNNER_USER}/certbot/conf:/etc/letsencrypt
    depends_on:
      - api
  api:
    image: grow-api:latest
    container_name: grow-api
    build: api
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
  certbot:
    image: certbot/dns-cloudflare:arm64v8-v1.25.0
    container_name: certbot
    volumes: 
      - /home/${GH_RUNNER_USER}/certbot/conf:/etc/letsencrypt
      - /home/${GH_RUNNER_USER}/certbot/logs:/var/log/letsencrypt
      - /home/${GH_RUNNER_USER}/certbot/cloudflare.ini:/cloudlfare.ini
    command: certonly --dns-cloudflare --dns-cloudflare-credentials /cloudflare.ini --force-renewal --email ${CLOUDFLARE_EMAIL} -d ${CLOUDFLARE_DOMAIN} --agree-tos