version: "3.8"
services:
  app:
    image: grow-app:latest
    container_name: grow-app
    build: app
    ports:
      - "80:80"
    volumes:
      - /home/pi/certbot/conf:/etc/letsencrypt
      - /home/pi/certbot/www:/var/www/certbot
    depends_on:
      - api
  api:
    image: grow-api:latest
    container_name: grow-api
    build: api
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
  certbot:
    image: certbot/certbot:arm64v8-v1.25.0
    container_name: certbot
    volumes: 
      - /home/pi/certbot/conf:/etc/letsencrypt
      - /home/pi/certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email correos@okkema.org -d grow.okkema.org --agree-tos