name: build
on:
  workflow_run:
    workflows: [test]
    types: [completed]
  workflow_dispatch:
env:
  branch: ${{ github.event_name == "workflow_run" && github.event.workflow_run.head_branch || github.event.workflow_dispatch.ref }}
  registry: ghcr.io
  image: ${{ github.repository }}
jobs:
  server:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.branch }}
      - name: Build and push grow-server
        uses: ./.github/actions/docker-build-push
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.image }}-server
          context: server 
  app:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.branch }}
      - name: Build and push grow-server
        uses: ./.github/actions/docker-build-push
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: ${{ env.image }}-app
          context: app
  client:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.branch }}
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install PlatformIO
        run: pip install platformio
      - name: Build with PlatformIO
        run: make client.build