name: build
on:
  workflow_run:
    workflows: [test]
    types: [completed]
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  server:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and push grow-server
        uses: ./.github/actions/docker-build-push
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ env.IMAGE_NAME }}-server
          context: server 
  app:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and push grow-server
        uses: ./.github/actions/docker-build-push
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ env.IMAGE_NAME }}-app
          context: app