name: Deploy to Raspberry Pi
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    env:
      CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
      CLOUDFLARE_DOMAIN: ${{ secrets.CLOUDFLARE_DOMAIN }}
      GH_RUNNER_USER: ${{ secrets.GH_RUNNER_USER }}
    steps:
      - uses: actions/checkout@v2
      - name: Deploy with Docker Compose
        run: sudo docker-compose up -d --build
        

