name: deploy
on:
  workflow_run:
    workflows: [test]
    types: [completed]
jobs:
  raspberry_pi:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Deploy with Docker Compose
        run: sudo docker-compose up -d --build