name: deploy
on:
  workflow_run:
    workflows: [build]
    types: [completed]
env:
  branch: ${{ github.event.workflow_run.head_branch }}
concurrency: deploy
jobs:
  raspberry_pi:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ env.branch }}
      - name: Deploy with Docker Compose
        run: sudo docker-compose up -d --build