name: Deploy to Raspberry Pi
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Deploy with Docker Compose
        run: docker build -t grow-api api
