name: publish
on:
  push:
    branches:
      - helm
jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: helm
      - name: Publish helm chart
        uses: helm/chart-releaser-action@v1.4.0
        with:
          charts_dir: k8s
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"