name: test
on:
  push:
  workflow_dispatch:
jobs:
  server:
    runs-on: ubuntu-latest
    env:
      TEST_INTEGRATION: True
    services:
      mariadb:
        image: mariadb:10.8.3
        env:
          MARIADB_DATABASE: grow
          MARIADB_ROOT_PASSWORD: password
        ports:
          - 3306:3306
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install poetry
        run: pipx install poetry
      - name: Generate requirements.txt
        working-directory: server
        run: poetry export --dev -o requirements.txt
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies with pip
        working-directory: server
        run: pip install -r requirements.txt
      - name: Run database migrations
        run: make server.migrations.upgrade
      - name: Test server with pytest
        run: make server.test
  client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install PlatformIO
        run: pip install platformio
      - name: Run tests with unity
        run: make client.test