name: Test
on:
  push:
    branches: [ test ]
  workflow_dispatch:
jobs:
  server:
    runs-on: ubuntu-latest
    env:
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r server/requirements.txt
      - name: Start SQL
        run: make sql.start
      - name: Test server with pytest
        run: make server.test
      - name: Stop SQL
        run: make sql.stop